# Generated by Django 4.2.4 on 2023-08-25 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0002_alter_employee_emp_id_alter_user_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp452', max_length=70),
        ),
    ]
